# -*- coding: utf-8 -*-
"""10 minutes to pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK2GtUzZ429StUF3vTNcJByaT4ETaRFf
"""

import numpy as np

import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

dates = pd.date_range('20130101', periods=6)

dates
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

df

df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'foo'})
   ...: 

In [10]: df2
df2
df2.dtypes

df.head()

df.tail(3)

df.index

df.columns

df.to_numpy()

df2.to_numpy()

df.describe()

df.T

df.sort_index(axis=1, ascending=False)

df.sort_values(by='B')

df['A']

df[0:3]

df['20130102':'20130104']